### PR TITLE
fixed bibeltv

### PR DESCRIPTION
**Pull request by freddii**
fixing https://github.com/jnk22/kodinerds-iptv/issues/329

### CODE REVIEW

**Review by freddii — COMMENTED** [review]
fixing https://github.com/jnk22/kodinerds-iptv/issues/325

**Review by freddii — COMMENTED** [review]
fixing https://github.com/jnk22/kodinerds-iptv/issues/160

**Review by freddii — COMMENTED** [review]
fixing https://github.com/jnk22/kodinerds-iptv/issues/270

**Comment by jnk22** [comment]
Thanks for your updates 👍 

You have used a dash-stream for gotv, which was usually added to list `iptv/dash/LIST-TYPE.m3u`.
Reason for that was the incompatibility of some clients back then. I think it was Tvheadend and Kodi not supporting it, I don't know about their current state.

I tried it with VLC and it does not work there as well (n-tv `https://pliventvuso-a.akamaihd.net/live/ntvhomelive/ntvhomelive.isml/.mpd` works, though).

But as it does not break anything that does not work anyway, we will keep it in the main list for now.

Did you test the gotv-URL with Kodi or Tvheadend?

**Comment by freddii** [comment]
Yes, the gotv link seams to be broken.

**Comment by plata** [comment]
@freddii if you use one of the supported keywords (see [here](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)), the resolved issues will be closed automatically when merging the PR.

**Pull request merged**
