### PR TITLE
update URL's of ZDF streams

### PR DESCRIPTION
**Pull request by masterbug**
updated stream urls of ZDF, ZDFneo, ZDFinfo, 3sat, Phoenix as mentioned in forum post https://www.kodinerds.net/index.php/Thread/56713-Kodinerds-IPTV-Fertige-Liste-mit-freien-IPTV-Kan%C3%A4len/?postID=541826#post541826

### CODE REVIEW

**Comment by masterbug** [comment]
hi, discoverd my tvheadend wont play ZDFinfo, checked the forum and there where those new URL's for ZDF streams. 
since i would like to see them fixed i did my first steps with git.

**Comment by Chris56** [comment]
The patch works fine!
How about also correcting
#244 
in one go?

**Comment by masterbug** [comment]
i also updated SWR streams, but the pull request still shows 5 changes instead of 7

**Comment by jnk22** [comment]
Thanks for these changes!
Unfortunately you only changed one file (pipe_tv.m3u), but for an URL update all URLs (in all categories kodi/clean/pipe and there respective sub-lists => 9 files) have to be updated.

Did that in #248 now :)

As stated in #248, ZDF and ZDFneo might be broken again soon, if those really are dynamic URLs. If so, please reopen any issue or open a new one for those.

**Pull request closed without merging**
