### PR TITLE
Remove all Russia Today Streams because of Russia's attack on Ukraine

### PR DESCRIPTION
**Pull request by bjoerns1983**
Maybe we should consider to remove the RT Streams from the list.
They show constant russian war propaganda, and i dont think they are a source of valid information regarding Russia's attack on Ukraine.

### CODE REVIEW

**Comment by bjoerns1983** [comment]
@jnk22 @freddii anyone has an opinion reagarding this topic?
if not i would simply follow the example of the EU which wants to stop RT spreading its program across Europe.

**Comment by Chris56** [comment]
I think it is very important to protect people from watching or listening to the enemy.
Especially Germans know only too well, how dangerous it will be to listen to the enemy's broadcasts.
Sometimes the sentence was even capital punishment, see
https://en.wikipedia.org/wiki/Feindsender , and
https://de.wikipedia.org/wiki/Feindsender
Therefore protect the people from harsh punishment and make sure they only listen to or watch streams with governmental approval.

**Comment by bjoerns1983** [comment]
Okay i remove them. If any of the staff is not okay with it they can be restored.

**Comment by Chris56** [comment]
@bjoerns1983 You can't do anything with irony, right ...?
Bye-bye Net Neutrality ...

**Comment by bjoerns1983** [comment]
An IPTV list curated by volunteers has nothing to do with net neutrality.
You can still fork the list and use with those channels included. It was already discussable to have these channels in the list before Russia started it attack on Ukraine.

**Comment by Chris56** [comment]
Ok, then call it
"Welcome Censorship" (of course, curated by volunteers)
instead of 
"Bye-bye Net Neutrality"

**Comment by bjoerns1983** [comment]
Fork it than you can do whatever you want with it.
Censoring would mean that we could stop you from watching these channels, we cant do that. 
We are only removing it from our list, because we think what Russia does is wrong.

**Comment by jnk22** [comment]
@Chris56 As @bjoerns1983 already stated, you are free to create a fork/your own lists with RT streams included.

Please also keep in mind, that this list is originated from the [Kodinerds forum](https://www.kodinerds.net/index.php/Thread/56713-Kodinerds-IPTV-Fertige-Liste-mit-freien-IPTV-Kan%C3%A4len/) and therefore a collaborative work.

That said, I do see a point in discussing what should be included and what should be excluded from this list in general.
Besides the banning of streams with copyright protected content, it is currently not clearly defined what should be included and what not. This is also true for more technical questions (e.g. radio streams, geo-blocked streams, ...)

This must be addressed and hopefully can solve future problems like this one.
Until that question is solved, I support @bjoerns1983 in removing these streams *at least temporarily*.

**Comment by Chris56** [comment]
@bjoerns1983 Ever thought about forking yourself a new branch with a clean (by your definition) stream list?
I heavily fight for the freedom of information (which necessarily is not depending of what I think is right or wrong)!
"Freedom is always the freedom of dissenters" (Rosa Luxemburg, killed by Nazis)

**Comment by bjoerns1983** [comment]
No why should i?
I think the decision is backed by the majority of people using this list. At least nobody besides of you, who never contributed to this list anyway, complained.
So if you want to spread a list which includes war propaganda, than fork it, go on, keep it up to date. Thats the nice thing about open source. 
RT was already a bad source of information when it came to Covid19, now it is only disgusting how they try to justify the Russian invasion.

**Comment by freddii** [comment]
https://twitter.com/elonmusk/status/1499982913949081600

**Comment by bjoerns1983** [comment]
Elon Musk is always cool with free speech until a student builds a twitter bot which tracks his privat jet.

**Comment by freddii** [comment]
„Einen guten Journalisten erkennt man daran, dass er sich nicht gemein macht mit einer Sache, auch nicht mit einer guten Sache“.

**Comment by mr2017x** [comment]
> Elon Musk is always cool with free speech until a student builds a twitter bot which tracks his privat jet.

OK, yes free press is cool, but who would like to be tracked like a dog? That's clearly something other.

Regarding russia today: Definitely pro keeping it in. Clearly it is pro russian (sure nobody would call it another and you dont have to like it ;-) ) ,but clever people can separate and compare. Stupid people believe or forbid or censor it. And censorship begins clearly at the point you (or the EU) started. Nobody at RT (as far as i know) said "kill all ukrainians" (or whatever), but i heard rumors that facebook/meta is now ok with that regarding russians - and EU and others hasn't anything said against (also as far as i know). so...clear also public tv/radio streams out? 

This is a dramatic political decision and should be done wisely, because breaches for other situations will be perhabs dramatic.

Sorry for keeping it up with politics, but this is a political decision, so we have to have an eye on it. 

Go deep into yourself @bjoerns1983 

BR

**Comment by bjoerns1983** [comment]
After reading the latest news about war crimes done by the russian soldiers which participate in this special operation, because it is not a war especially not for propaganda channels like RT, i think i am still okay with removing the channels from the list.
If you want to have the channels back in than fork the list or ask any of the other Team members to include it again.
I think maybe @freddii would do that, from his comments i could recon that is not okay with the decision to remove those streams.

**Comment by mr2017x** [comment]
> After reading the latest news about war crimes done by the russian soldiers which participate in this special operation, because it is not a war especially not for propaganda channels like RT, i think i am still okay with removing the channels from the list. If you want to have the channels back in than fork the list or ask any of the other Team members to include it again. I think maybe @freddii would do that, from his comments i could recon that is not okay with the decision to remove those streams.

presumed, so far, furthermore i read some minutes ago in the times that a ukrainian village killed 2 soldiers and injured more by poisoned pies (Times) - either this is also a war crime or makes those village's people to combatants and therefore to legal targets. Some papers write it is OK that ukrainian soldiers injuring russian forces after they already catched and disarmed them, is this OK?

Who knows what has happened, exactly therefore we shouldn't start opening the door for censorship like removing sources which are definitely also not neutral but could give another view and sometimes also a hint or perspective others don't tell. 

So far going into deep about your political decision...

So i am for holding it in the list.

**Pull request merged**
