### PR TITLE
Add Livestream for DLX Music Channels, Fix of Regio TV Schwaben

### PR DESCRIPTION
**Pull request by skick3**
Add Livestream for DLX Music Channels
Fix of Regio TV Schwaben

### CODE REVIEW

**Comment by bjoerns1983** [comment]
Could you please add Logo's for the Deluxe Music Channels?

**Comment by skick3** [comment]
> Could you please add Logo's for the Deluxe Music Channels?
Is it legal to use images without being asked by the rights provider?

**Comment by bjoerns1983** [comment]
According to the Wikipedia such simple Logos do not meet the threshold of originality:
https://commons.wikimedia.org/wiki/File:DELUXE_MUSIC_Logo_2019.png

**Comment by skick3** [comment]
I chose the safer way, because an integrated Kontor brand logo is guaranteed not to be freely usable. Got the image source/images from the website for now

**Comment by bjoerns1983** [comment]
Regarding the Kontor Logo:
https://commons.wikimedia.org/wiki/File:Logo_Kontor_Records.svg

**Comment by skick3** [comment]
Due to kindergarten because of unimportant station logos or not uploaded legally protected station logos on a third-party platform on the Internet, the pull request is closed.

**Pull request closed without merging**
