### PR TITLE
added DW+

### PR DESCRIPTION
**Pull request by freddii**
fixing:
https://github.com/jnk22/kodinerds-iptv/issues/317

### CODE REVIEW

**Review by freddii — COMMENTED** [review]
use working stream for Rai News 24
use HD stream for NRWision

**Review by freddii — COMMENTED** [review]
use working stream for NASA TV

**Review by freddii — COMMENTED** [review]
added Radio Bremen TV 
fixing:
https://github.com/jnk22/kodinerds-iptv/issues/321
https://github.com/jnk22/kodinerds-iptv/issues/217

**Review by freddii — COMMENTED** [review]
added EbS and EbS+
fixing:
https://github.com/jnk22/kodinerds-iptv/issues/225

**Review by freddii — COMMENTED** [review]
fixing:
https://github.com/jnk22/kodinerds-iptv/issues/283

**Review by freddii — COMMENTED** [review]
fixed streams for ok4 (Koblenz) and ok54 (Trier)

**Review by freddii — COMMENTED** [review]
Updated streams for SDF and Okto
TRP1 became Niederbayerntv (https://de.wikipedia.org/wiki/Niederbayern_TV_Passau)

**Review by freddii — COMMENTED** [review]
removed also Donau TV and Isar TV 
cause they became with TRP1 now Niederbayerntv

**Review by freddii — COMMENTED** [review]
fixed 9 more channels:
regio tv schwaben
RFO stream
Westerwald TV
Allgäu TV
Franken Fernsehen
oldenburg eins
Rhein Neckar Fernsehen
SBN
GOD TV

**Comment by jnk22** [comment]
Great work! I‘ll have a look at your changes in the next few days! 👍

**Comment by jnk22** [comment]
It seems that you have deleted your repository, therefore I cannot merge this PR directly (with all the commits in your name).

grafik

If you prefer to have the commits linked to your name/account, you can re-fork this repository and try to re-open this PR or copy your content and create a new PR with it.

Otherwise I could copy the changes you made and re-submit a PR with your content and merge it into the master branch myself.

As you have put a lot of effort into these changes I would really like you to keep all the credits for it, but if you do not care about it and if it is easier for you if I create a new PR with your changes, I can do that as well. Just tell me how you prefer it :)

And thank you for all your updates! 👍

**Comment by freddii** [comment]
i do not care about credits.

**Comment by jnk22** [comment]
Done :)

**Comment by freddii** [comment]
:)

**Pull request closed without merging**
