### PR TITLE
fix: update NDR channels

### PR DESCRIPTION
**Pull request by poika-xy**
Fixes HLS stream URLs

### CODE REVIEW

**Comment by bjoerns1983** [comment]
Would you mind using the generice master.m3u8 instead of the master_720.m3u8?
So the client could switch between the different resolutions depending on the network speed.

**Comment by poika-xy** [comment]
Personally, I do prefer the master.m3u8 too.
In https://github.com/jnk22/kodinerds-iptv/issues/406#issuecomment-817636938 it said:
`direct high quality streams > master streams* (eg. index_3096_av-p.m3u8 vs master.m3u8)`
and
`*The reason for this have been the faster channel switches in the past. This however requires frequent changes to stream URLs as most of you have seen in the past. The 'master' link should be working even when a direct stream URL would have to be changed.`

Therefore I extracted the highest resolution stream.

Could one of the maintainers please state a clear policy (on which .m3u8 URL to choose) in either:
https://github.com/jnk22/kodinerds-iptv/blob/master/CONTRIBUTING.md
or
https://github.com/jnk22/kodinerds-iptv/blob/master/README.md

**Comment by jnk22** [comment]
@poika-xy You are right, this has not been properly defined before. I have created a PR with an updated **CONTRIBUTING.md** file: #571

**Comment by bjoerns1983** [comment]
Okay should be clear now.
@poika-xy would you add the master.m3u8 links or should i do that?

**Comment by poika-xy** [comment]
Ok, everything should be ready to merge. All stream URLs were tested.

@jnk22 @bjoerns1983  Thank you for adding clarifying statements :)

**Pull request merged**
