### PR TITLE
fix streams - BR Süd, RT, RT Documentary

### PR DESCRIPTION
**Pull request by gsantner**
Update a few broken URLs that don't work. (BTW, some kind of automatic checks would be a good idea - just a simple HTTP-HEAD check for 200 can already tell most broken streams).

* fixed RT Documentary stream, source `https://rtd.rt.com/on-air/`
* fixed RT UK stream, source `https://www.rt.com/on-air/rt-uk-air/rt-player/`
* fixed BR Süd stream, old stream `https://mcdn.br.de/br/fs/bfs_sued/hls/de/master.m3u8` produces errors, it suggests a new URL and that one actually works.

hints for future additions (yes streams m3u8 URLs do work and can be easily found):  
* (EN) CGTN  - `https://www.cgtn.com/channel/documentary`
* (DE) BILD TV - see kodinerds forum thread
* (DE) BR Panorama
* (AT) Hitradio Ö3 webcam `https://oe3.orf.at/programm/stories/livecam/`

### CODE REVIEW

**Comment by bjoerns1983** [comment]
Thanks for your additions.
Actually i tried the old BR Süd link and it worked, when i look at it at the website there is a http 302 to the link you provided. I hope that that link stays stable, else we have to revert back.
Bild TV is already included in the list.

For future additions you only have to change the source.yaml, everything else will be generated automatically.

**Comment by freddii** [comment]
Hitradio Ö3 webcam is also already on list as Ö3-VisualRadio

**Comment by gsantner** [comment]
> also the old br-süd link is working for me.

have you tried something else other than Kodi? At mpv/ffmpeg it errored, as written in the commit description

Suggestions: OK, didn't notice 😄 . So only CGTN & BR Panorama isn't there it seems

**Comment by freddii** [comment]
with mpv 0.33.1-1+b2 

mpv https://mcdn.br.de/br/fs/bfs_sued/hls/de/master.m3u8
[ffmpeg] https: Cannot reuse HTTP connection for different host: brcdn.vo.llnwd.net:-1 != mcdn.br.de:-1
[ffmpeg/demuxer] hls: keepalive request failed for 'https://mcdn.br.de/br/fs/bfs_sued/hls/de/master_480p_578.m3u8' with error: 'Invalid argument' when parsing playlist
[ffmpeg] https: Cannot reuse HTTP connection for different host: brcdn.vo.llnwd.net:-1 != mcdn.br.de:-1
[ffmpeg/demuxer] hls: keepalive request failed for 'https://mcdn.br.de/br/fs/bfs_sued/hls/de/master_1280p_3628.m3u8' with error: 'Invalid argument' when parsing playlist
[ffmpeg] https: Cannot reuse HTTP connection for different host: brcdn.vo.llnwd.net:-1 != mcdn.br.de:-1
[ffmpeg/demuxer] hls: keepalive request failed for 'https://mcdn.br.de/br/fs/bfs_sued/hls/de/master_960p_1928.m3u8' with error: 'Invalid argument' when parsing playlist
     Video --vid=1 (h264 640x360 50.000fps) (1289 kbps)
     Video --vid=2 (h264 480x270 50.000fps) (715 kbps)
 (+) Video --vid=3 (h264 1280x720 50.000fps) (4607 kbps)
     Video --vid=4 (h264 960x540 50.000fps) (2438 kbps)
     Audio --aid=1 (aac 2ch 48000Hz) (1289 kbps)
     Audio --aid=2 (aac 2ch 48000Hz) (715 kbps)
 (+) Audio --aid=3 (aac 2ch 48000Hz) (4607 kbps)
     Audio --aid=4 (aac 2ch 48000Hz) (2438 kbps)
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 yuv420p
AV: 00:00:01 / 00:00:07 (25%) A-V:  0.000 Cache: 5.6s/2MB

and stream keeps playing.

**Comment by freddii** [comment]
maybe more people use an old mpv/ffmpeg version, so i think keeping your link is a good idea.

**Comment by bjoerns1983** [comment]
Normally i try all links with VLC, because that is what i always have "on hand" on my Laptop.
Right now i try to get a little bash script running which "parses" the sources.yaml and gets the http status codes of the stream adresses.

**Comment by gsantner** [comment]
this is what I used in the past. maybe it helps:
```
#!/bin/bash
UA="Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)"
streamsm3u=`realpath streams.m3u`
streams=`cat streams.m3u | grep "^http" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//' | grep -v EXTM3U`

cd `mktemp -d`
for stream in $streams ; do
	stream=${stream%$'\r'}
	httpcode=`curl -I -L -X GET -A "$UA" "$stream" 2>/dev/null | grep "^HTTP" | cut -d$' ' -f2 | xargs`
	if [[ "$httpcode" != *"200"* ]] ; then
		[ "$httpcode" == "" ] && httpcode="???"
		name=`cat "$streamsm3u" | grep -B 1  "$stream" | head -n1 | tr -s '[:blank:]'`
		echo "Broken ($httpcode) :: $name"
		echo "                $stream"
		echo ""
	fi
done
```

Though, also check out the mentioned util in <https://github.com/jnk22/kodinerds-iptv/issues/421>, it's giving less errors.

**Comment by gsantner** [comment]
this is what I used in the past. maybe it helps:

grafik

```
#!/bin/bash
UA="Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)"
streamsm3u=`realpath streams.m3u`
streams=`cat streams.m3u | grep "^http" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//' | grep -v EXTM3U`

cd `mktemp -d`
for stream in $streams ; do
	stream=${stream%$'\r'}
	httpcode=`curl --max-time 10 -I -L -X GET -A "$UA" "$stream" 2>/dev/null | grep "^HTTP" | cut -d$' ' -f2 | xargs`
	if [[ "$httpcode" != *"200"* ]] ; then
		[ "$httpcode" == "" ] && httpcode="???"
		name=`cat "$streamsm3u" | grep -B 1  "$stream" | head -n1 | tr -s '[:blank:]'`
		echo "Broken ($httpcode) :: $name"
		echo "                $stream"
		echo ""
	fi
done
```

Though, also check out the mentioned util in `https://github.com/jnk22/kodinerds-iptv/issues/421`, it is better.

**Comment by bjoerns1983** [comment]
Okay here is a list of Streams which produce a 404:
https://orf2.mdn.ors.at/out/u/orf2/q6a/manifest_6.m3u8
https://cdnapisec.kaltura.com/p/1719221/sp/171922100/playManifest/entryId/1_4dmq7avs/format/applehttp/protocol/https/a.m3u8
http://klive-a.akamaihd.net/dc-1/live/hls/p/1719221/e/1_0mc3z57p/sd/10000/t/XTGwenpKUhx_fbVnsiu9MQ/index-s32.m3u8
http://klive-a.akamaihd.net/dc-1/live/hls/p/1719221/e/1_ljzy3evp/sd/10000/t/nwOKUovT2mwnA8x_KnC4zg/index-s32.m3u8
https://tvnzioslive04-i.akamaihd.net/hls/live/267188/1924997895001/channel1/masterR_5.m3u8
https://tvnzioslive05-i.akamaihd.net/hls/live/267189/1924997895001/channel2/masterR_55.m3u8
https://bfmtvalive1-a.akamaihd.net/8a3483ffeb9d40f0a738c1392f2bcc14/eu-central-1/876450610001/profile_0/da8e1b0dc391423390d09277e66af0b9/chunklist_ssaiM.m3u8
https://livestream.goinfo.it/SDFLive/sdfros/playlist.m3u8
http://82.76.40.76/digi24edge/smil:digi24.smil/chunklist_w41349427_b2830400_sleng.m3u8
http://livestream.realitatea.net/livestream/liverealitatea.stream/chunklist.m3u8
https://tv-trtworld.live.trt.com.tr/master_1080.m3u8
https://w1.kringvarp.fo/uttanlands/_definst_/smil:uttanlands.smil/chunklist_w121411721_b5000000_slfao.m3u8
https://wowzaprod133-i.akamaihd.net/hls/live/577385/a1e0ad3f/a1e0ad3f_1_1376000/chunklist.m3u8
http://sdn-global-live-http-cache.3qsdn.com/live/_definst_/smil:5713-mbr.smil/chunklist_b2000000.m3u8
https://ddxc58gl29qdx.cloudfront.net/p/GERG_1280x720_3000k.m3u8
http://62.113.221.4/tv2000plus-live/_definst_/mp4:livestream/playlist.m3u8
https://cmctv.ios.internapcdn.net/cmctv_vitalstream_com/live_1/CMC-TV/chunklist.m3u8

And these one deliver a Bad Request (400), which must not mean that they dont work:
https://orf-live.ors-shoutcast.at/fm4-q2a
https://orf-live.ors-shoutcast.at/oe3-q2a
https://securestream.o94.at/live.mp3
https://orf-live.ors-shoutcast.at/oe1-q2a
https://orf-live.ors-shoutcast.at/campus-q2a
https://orf-live.ors-shoutcast.at/noe-q2a
https://orf-live.ors-shoutcast.at/stm-q2a
https://orf-live.ors-shoutcast.at/tir-q2a
https://orf-live.ors-shoutcast.at/wie-q2a
http://koelncampus.uni-koeln.de:80/hq
https://rqstream.radioq.de/stream/192.mp3
http://icecast.l-uni.co:8001/lunico_high_mp3
http://stream.radiohertz.de/hertz-hq.mp3
http://stream.multicult.fm:8000/hifi
http://radio.oeins.de:8000/oeins
http://pool.radiopaloma.de/RADIOPALOMA.mp3
http://87.118.122.220:8002/stream
http://37.187.93.104:8414/stream
http://159.69.217.78:8000/?radio=radio2000.mp3
http://zdf0304-lh.akamaihd.net/i/de03_v1@392855/index_3096_av-p.m3u8
http://zdf0304-lh.akamaihd.net/i/de04_v1@392856/index_3096_av-p.m3u8
http://zdf0506-lh.akamaihd.net/i/de05_v1@392857/index_3096_av-p.m3u8
http://zdf0506-lh.akamaihd.net/i/de06_v1@392858/index_3096_av-p.m3u8
http://zdf0708-lh.akamaihd.net/i/de07_v1@392868/index_3096_av-p.m3u8
http://zdf0708-lh.akamaihd.net/i/de08_v1@392869/index_229_av-b.m3u8
https://arteevent01-lh.akamaihd.net/i/arte_event01@395110/index_1_av-p.m3u8
https://arteevent02-lh.akamaihd.net/i/arte_event02@308866/index_1_av-p.m3u8
https://arteevent03-lh.akamaihd.net/i/arte_event03@305298/index_1_av-p.m3u8
https://arteevent04-lh.akamaihd.net/i/arte_event04@308879/index_1_av-p.m3u8
http://swr_event01_uni-lh.akamaihd.net/i/swr_event01@112805/index_3584_av-p.m3u8
http://swr_event02_uni-lh.akamaihd.net/i/swr_event02@112806/index_3584_av-p.m3u8
http://swr_event04_uni-lh.akamaihd.net/i/swr_event04@198169/index_3584_av-p.m3u8
http://ndr_spezial-lh.akamaihd.net/i/spezial_1@119227/index_3776_av-p.m3u8
http://ndr_spezial-lh.akamaihd.net/i/spezial_2@119228/index_3776_av-p.m3u8
http://ndr_spezial-lh.akamaihd.net/i/spezial_3@119229/index_3776_av-p.m3u8
http://ndr_spezial-lh.akamaihd.net/i/spezial_4@119230/index_3776_av-p.m3u8
http://ndr_spezial-lh.akamaihd.net/i/spezial_5@384495/index_3776_av-p.m3u8
http://ndr_spezial-lh.akamaihd.net/i/spezial_6@364638/index_3776_av-p.m3u8
http://liveevent1.mdr.de/i/livetvmdrevent1_ww@106904/index_3871_av-p.m3u8
http://liveevent2.mdr.de/i/livetvmdrevent2_ww@106905/index_3871_av-p.m3u8
http://liveevent2.mdr.de/i/livetvmdrevent3_ww@106905/index_3871_av-p.m3u8

**Pull request merged**
